version: '2'
services:

  mom:
    image: ${image.registry}apm-em:${project.version}
    #mem_limit: 2000m
    command: mom
    ports:
    - "5001:5001"
    - "8081:8081"
    - "8082:8080"
    environment:
      - HEAP_XMX=${env.memory}
    #volumes:
      #- ./:/opt/ca/logs
      #- ~/docker-introscope/transfer/xmltv:/transfer/xmltv
      #- ~/docker-introscope/transfer/modules:/transfer/modules